services:
  db:
    image: postgres:16.6-alpine
    container_name: integration-tests
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
